#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i 's/add_header X-Served-By.*;/add_header X-Served-By $hostname;/' /etc/nginx/sites-available/default
# Restart Nginx service to apply changes
service nginx restart
echo "Nginx configured with custom HTTP header: X-Served-By"

